# audacious
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/audacious.1.gz
complete -c audacious -s h -l help -d 'Show a brief list of options. SS Opening files:'
complete -c audacious -s e -l enqueue -d 'Add the files on the command line to the current playlist but do not start pl…'
complete -c audacious -s E -l enqueue-to-temp -d 'Add the files on the command line to the ``Now Playing\'\' playlist and start p…'
complete -c audacious -s p -l play -d 'Start playback.   If paused, playback will resume from the same point'
complete -c audacious -s u -l pause -d 'Pause playback, or resume if already paused'
complete -c audacious -s t -l play-pause -d 'Equivalent to --pause if playback is active, otherwise --play'
complete -c audacious -s s -l stop -d 'Stop playback'
complete -c audacious -s r -l rew -d 'Skip to the previous song in the playlist'
complete -c audacious -s f -l fwd -d 'Skip to the next song in the playlist. SS Miscellaneous:'
complete -c audacious -s m -l show-main-window -d 'Show the Audacious window if it is hidden and bring it to the top'
complete -c audacious -s j -l show-jump-box -d 'Show the Jump to Song window'
complete -c audacious -s H -l headless -d 'Start in command-line mode; i. e. , without any graphical user interface'
complete -c audacious -s q -l quit-after-play -d 'Exit as soon as playback stops, or immediately if there is nothing to play'
complete -c audacious -s v -l version -d 'Print version information and exit'
complete -c audacious -s V -l verbose -d 'Print debugging output while running (may be used twice for even more output)'
complete -c audacious -s N -l new-instance -d 'Starts a new instance'

