# galculator
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/galculator.1.gz
complete -c galculator -s h -l help -d 'Show summary of options'
complete -c galculator -s v -l version -d 'Show version of program'

