# lxqt-leave
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/lxqt-leave.1.gz
complete -c lxqt-leave -l logout
complete -c lxqt-leave -l lockscreen
complete -c lxqt-leave -l suspend
complete -c lxqt-leave -l hibernate
complete -c lxqt-leave -l shutdown
complete -c lxqt-leave -l reboot
complete -c lxqt-leave -l help

