# pcmanfm-qt
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/pcmanfm-qt.1.gz
complete -c pcmanfm-qt -s h -l help -d 'Show help options . SS "Application Options:"'
complete -c pcmanfm-qt -s p -l profile -d 'Set name of configuration profile'
complete -c pcmanfm-qt -s d -l daemon-mode -d 'Run PCManFM as a daemon'
complete -c pcmanfm-qt -l quit -d 'Quit PCManFM'
complete -c pcmanfm-qt -l desktop -d 'Launch desktop manager'
complete -c pcmanfm-qt -l desktop-off -d 'Turn off desktop manager if it\'s running'
complete -c pcmanfm-qt -l desktop-pref -d 'Open desktop preference dialog on the page with the specified name'
complete -c pcmanfm-qt -s w -l set-wallpaper -d 'Set desktop wallpaper from image FILE'
complete -c pcmanfm-qt -l wallpaper-mode -d 'Set mode of desktop wallpaper.  MODE=(color|stretch|fit|center|tile)'
complete -c pcmanfm-qt -l show-pref -d 'Open Preferences dialog on the page with the specified name'
complete -c pcmanfm-qt -s n -l new-window -d 'Open new window'
complete -c pcmanfm-qt -s f -l find-files -d 'Open Find Files utility AUTHORS pcmanfm-qt was primarily written by Hong Jen …'

