# pdftohtml
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/pdftohtml.1.gz
complete -c pdftohtml -s f -d 'Specifies the first page to convert'
complete -c pdftohtml -s l -d 'Specifies the last page to convert'
complete -c pdftohtml -s z -d 'Specifies the initial zoom level.   The default is 1. 0, which means 72dpi, i'
complete -c pdftohtml -s r -d 'Specifies the resolution, in DPI, for background images'
complete -c pdftohtml -o nofonts -d 'Disable extraction of embedded fonts'
complete -c pdftohtml -o skipinvisible -d 'Don\'t draw invisible text'
complete -c pdftohtml -o allinvisible -d 'Treat all text as invisible'
complete -c pdftohtml -o opw -d 'Specify the owner password for the PDF file'
complete -c pdftohtml -o upw -d 'Specify the user password for the PDF file'
complete -c pdftohtml -s q -d 'Don\'t print any messages or errors. RB "[config file: " errQuiet ]'
complete -c pdftohtml -o cfg -d 'Read  config-file in place of ~/. xpdfrc or the system-wide config file'
complete -c pdftohtml -s v -d 'Print copyright and version information'
complete -c pdftohtml -s h -d 'Print usage information.  ( -help and'
complete -c pdftohtml -l help -d 'are equivalent. )'

