# xrdp-sesman
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/xrdp-sesman.8.gz
complete -c xrdp-sesman -s k -l kill -d 'Kills running xrdp-sesman daemon'
complete -c xrdp-sesman -s h -l help -d 'Output help information and exit'
complete -c xrdp-sesman -s v -l version -d 'Output version information and exit'
complete -c xrdp-sesman -s n -l nodaemon -d 'Starts xrdp-sesman in foreground instead of starting it as a daemon'
complete -c xrdp-sesman -l dump-config -d 'Print the configuration on stdout before starting the daemon'

