# xrdp-sesrun
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/xrdp-sesrun.8.gz
complete -c xrdp-sesrun -s g -d 'Set session geometry'
complete -c xrdp-sesrun -s b -d 'Set session bits-per-pixel (colour depth).  Some session types (i. e'
complete -c xrdp-sesrun -s s -d 'Server on which sesman is running (probably \'localhost\')'
complete -c xrdp-sesrun -s t -d 'Session type - one of Xorg, Xvnc or X11rdp'
complete -c xrdp-sesrun -s D -d 'Directory to run the new session in'
complete -c xrdp-sesrun -s S -d 'Specify an alternate shell to run, instead of the default window manager'
complete -c xrdp-sesrun -s p -d 'Password for user'
complete -c xrdp-sesrun -s F -d 'Specify a file descriptor (normally 0) to read the password in from'

