# xrdp
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/xrdp.8.gz
complete -c xrdp -s k -l kill -d 'Kill running xrdp daemon'
complete -c xrdp -s h -l help -d 'Output help information and exit'
complete -c xrdp -s v -l version -d 'Output version information and exit'
complete -c xrdp -s n -l nodaemon -d 'Start xrdp in foreground instead of starting it as a daemon'
complete -c xrdp -s p -l port -d 'Specify TCP port to listen to.  This overrides port setting in xrdp. ini file'
complete -c xrdp -s f -l fork -d 'Fork a new process on a new connection'
complete -c xrdp -l dump-config -d 'Print the configuration on stdout before starting the daemon'

