# xrdp-sesadmin
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/xrdp-sesadmin.8.gz
complete -c xrdp-sesadmin -s u -d 'Username for authentication on the server.  Defaults to root'
complete -c xrdp-sesadmin -s p -d 'The password to authenticate with'
complete -c xrdp-sesadmin -s s -d 'The host address of the server to connect to.  Defaults to localhost'
complete -c xrdp-sesadmin -s i -d 'The TCP port number to connect to.  Defaults to 3350'
complete -c xrdp-sesadmin -s c -d 'Specifies the command to execute on the server.  Valid commands are: . RS 4'

